### ISSUE TITLE
Comment Directive not working according to documentation

### ISSUE THREAD

**Issue by atilacamurca** [guidesmiths/marv#1]
According to <https://github.com/guidesmiths/marv#comment-directive> the comment directive supports

```
-- @MARV COMMENT = A much longer comment that can contain full stops. Yay!
```

but when I execute that in the database I only get `A`.

**Comment by cressie176** [comment]
Hi @atilacamurca. Thanks for reporting. Which driver are you using?

**Comment by cressie176** [comment]
Found it. Fixing now.

**Comment by atilacamurca** [comment]
it was postgresql

**Comment by cressie176** [comment]
Releasing a fix now.

**Comment by cressie176** [comment]
Please upgrade to marv 1.4.2 and marv-pg-driver 1.1.1. Sorry for the trouble.

**Comment by atilacamurca** [comment]
now it's working correctly, thanks so very much for this project.

PS.: I'm working on a desktop version of a migration tool based on marv and electron

<https://github.com/open-fidias/db-migration-app>

I hope we can work together to continue to improve both apps.

**Comment by cressie176** [comment]
Good stuff. Happy to consider changes you need.
