### ISSUE TITLE
Discrepancy in the README

### ISSUE THREAD

**Issue by aegatlin** [guidesmiths/marv#22]
You mention in the readme under "what marv doesn't do" that you do not support checksums (yet), but then in the next section "important notes about transactions" you write that if something goes awry the user will have to update a checksum column in the migrations table. 

Does that mean you *do* support checksums? If you don't, then what are you using the current checksums for? And also how do you ensure migration integrity without them?

I'm excited to try marv, thank you for building it :D

**Comment by cressie176** [comment]
Hi @aegatlin,

> Checksum validation (we may implement this in future)

Marv doesn't *validate* the checksums, which means you can change the contents of a migration script after it's been run and Marv won't complain. However it does record the checksum in the DB. If you need to manually insert a migration record, then you will also need to generate a checksum. Hence the note.

**Comment by aegatlin** [comment]
Thank you for the reply.

What is the purpose of the checksum, then?

**Comment by cressie176** [comment]
It was for future proofing. I wasn't sure if I would add the checksum validation, but without storing checksums from day one it would have been more difficult.

**Comment by cressie176** [comment]
@aegatlin OK to close?

**Comment by aegatlin** [comment]
Yes, thank you.
