### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by aegatlin** [guidesmiths/marv#23]
Any plans to add declaration files?

**Comment by cressie176** [comment]
Hi @aegatlin,
No - I have no plans to add typescript support.

**Comment by aegatlin** [comment]
Thank you for the reply.

Are you open to PRs that add declaration files?

**Comment by cressie176** [comment]
I've personally little interest in typing dynamic languages, and so would not want the additional maintenance that comes with type definition, but am happy to discuss things a bit further. Considering the following 

```
const migrations = await marv.scan(directory, scanOptions);
const driver = pgDriver(driverOptions);
await marv.migrate(migrations, driver, migrationOptions));
```

I would imagine the TypeScript definitions would have to define `migrations` and each of the `options`, which means I would have to update the definitions whenever the options or migrations structure changed. The driver type would vary depending on whether pg, mysql, oracle, sqlite or mssql was used, as would the driver options - which are passed straight through to the underling db client.

**Comment by cressie176** [comment]
@aegatlin any further thoughts or OK to close?

**Comment by aegatlin** [comment]
Hello, I agree with your assessment of the work to include types for Typescript support. Seems reasonable to not want that additional work at this time. Thank you for your reply and kindness in answering my questions :D

**Comment by rjoonas** [comment]
I recently wrote TS declaration files for marv and marv-pg-driver and contributed them to DefinitelyTyped so you can just install `@types/marv` and `@types/marg-pg-driver`:

https://www.npmjs.com/package/@types/marv
https://www.npmjs.com/package/@types/marv-pg-driver
