### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by benkeil** [guidesmiths/marv#37]
Would be nice to have types.

**Comment by cressie176** [comment]
Hi @benkeil,
Thanks for the suggestion, but I'm not interested in adding + maintaining TypeScript types.

**Comment by rjoonas** [comment]
I recently wrote TS declaration files for marv and marv-pg-driver and contributed them to DefinitelyTyped so you can just install `@types/marv` and `@types/marg-pg-driver`:

https://www.npmjs.com/package/@types/marv
https://www.npmjs.com/package/@types/marv-pg-driver
